[package]
name = "hyprclikr"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31.4"
uinput = "0.1.3"
gtk4 = "0.10.0"
glib = "0.21.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xdg = "3"
